services:
  app:
    build: .
    container_name: image_server_app2
    restart: unless-stopped
    volumes:
      - ./images:/app/images
      - ./logs:/app/logs
    expose:
      - "8000"

  nginx:
    image: nginx:1.27
    container_name: image_server_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./images:/images:ro
    ports:
      - "8080:80"
      - "80:80"
    restart: unless-stopped

volumes:
  images:
  logs:


